# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    branches: [ "master", "devel" ]
  pull_request:
    branches: [ "master", "devel" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v3
      with:
        java-version: '21'
        # TODO: switch to 'temurin' as soon as it's available
        distribution: 'zulu'
    - name: Validate Gradle wrapper
      uses: gradle/wrapper-validation-action@v1
    - name: Preparations
      shell: bash
      run: chmod +x gradlew
    - name: Build with Gradle
      uses: gradle/gradle-build-action@v2
      with:
        arguments: build
